arabel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from markdownx import urls as markdownx

urlpatterns = [
    url(r'', include('website.urls')),
    path('admin/', admin.site.urls),

    url(r'^markdownx/', include(markdownx))
]

website/urls.py
from django.urls import path

from website import views

urlpatterns = [
    path('', views.index, name='website-index'),
    path('about', views.about, name='website-about'),
    path('squares', views.explore_by_square, name='website-squares'),
    path('square_search', views.square_search, name='website-square-search'),
    path('square_details/<int:square_id>', views.square_details, name='website-square-details'),
    path('publication_details', views.publication_details, name='website-publication_details'),

    path('api/available-species', views.available_species_json, name='available-species-json'),
    path('api/squares_for_occurrences', views.squares_for_occurrences_json, name='squares-for-occurrences-json'),
    path('api/occurrences', views.occurrences_json, name='occurrences-json'),
    path('api/counters', views.counters_json, name='counters-json')
]

website/models.py
from django.contrib.gis.db import models
from django.urls import reverse


class Publication(models.Model):  # = Access table "LITTERATUUR"
    access_id = models.CharField(max_length=50, unique=True)
    code = models.CharField(max_length=50, unique=True)
    year = models.IntegerField()
    still_checking = models.BooleanField()  # "Nog controlleren" in source data
    not_relevant = models.BooleanField()  # "Niet relevant"
    ingegeven = models.BooleanField()
    publication = models.TextField()


class Family(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Families"


class RedListStatus(models.Model):
    access_id = models.IntegerField()
    name = models.CharField(max_length=255)


class Species(models.Model):
    fsc = models.CharField(max_length=50, unique=True)  # This is the PK in access, it appears to be the family code concatenated with a species code
    family = models.ForeignKey(Family, on_delete=models.PROTECT)
    scientific_name = models.CharField(max_length=255)
    scientific_name_w_authorship = models.CharField(max_length=255)
    vernacular_name_nl = models.CharField(max_length=255, blank=True)
    redlist_status = models.ForeignKey(RedListStatus, on_delete=models.PROTECT, blank=True, null=True)

    def as_dict(self):
        return {
            "id": self.pk,
            "scientific_name": self.scientific_name,
            "family_id": self.family_id,
            "family_name": self.family.name,
            "vernacular_name_nl": self.vernacular_name_nl,
            "redlist_status_text": self.redlist_status.name
        }

    def __str__(self):
        return self.scientific_name

    class Meta:
        verbose_name_plural = "Species"
        ordering = ['scientific_name']


class NoMGRSData(Exception):
    pass


class MgrsSquare(models.Model):
    name = models.CharField(max_length=9)
    gzd = models.CharField(max_length=3)
    poly = models.PolygonField()

    def get_absolute_url(self):
        return reverse('website-square-details', kwargs={"square_id": self.pk})

    def as_dict(self):
        return {
            'id': self.pk,
            'gzd': self.gzd,
            'name': self.name,
            'geojson_str': self.poly.json
        }


def get_mgrs_prefix(code):
    if code[0] == 'K' or code[0] == 'L':
        return '32U'
    else:
        return '31U'


class Station(models.Model):
    staal_id = models.CharField(max_length=50, unique=True)  # PK in Access
    station_name = models.CharField(max_length=50)
    area = models.CharField(max_length=255, blank=True)  # "Gebied" in access
    subarea = models.CharField(max_length=255, null=True)  # "Deelgebied" in Access

    utm10_code = models.CharField(max_length=4, blank=True)
    utm5_code = models.CharField(max_length=5, blank=True)
    utm1_code = models.CharField(max_length=6, blank=True)

    leg = models.CharField(max_length=255, blank=True)
    det = models.CharField(max_length=255, blank=True)
    habitat_description = models.CharField(max_length=255, blank=True)  # Biotoopomschrijving

    begin_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    publication_reference = models.CharField(max_length=50, blank=True)  # reference to publication code, as a string straight from Access
    publication = models.ForeignKey(Publication, on_delete=models.PROTECT, null=True, blank=True)

    most_detailed_square = models.ForeignKey(MgrsSquare, blank=True, null=True, on_delete=models.PROTECT, related_name='stations_mostdetailed_set')
    _5_or_10_square = models.ForeignKey(MgrsSquare, blank=True, null=True, on_delete=models.PROTECT, related_name='stations_5or10_set')

    class Meta:
        ordering = ['station_name']

    def most_detailed_mgrs_identifier(self , limit_to_5=False):
        """Return the identifier and type (1-5-10)

        if limit_to_5 is True, avoid returning 1km square even if we have them (might bring confusion on the map,
        see https://github.com/niconoe/arabel/issues/8.
        """
        if self.utm1_code != '' and limit_to_5 is False:
            return (f"{get_mgrs_prefix(self.utm1_code)}{self.utm1_code}", 1)
        elif self.utm5_code != '':
            return (f"{get_mgrs_prefix(self.utm5_code)}{self.utm5_code}", 5)
        elif self.utm10_code != '':
            return (f"{get_mgrs_prefix(self.utm10_code)}{self.utm10_code}", 10)
        else:
            raise NoMGRSData

    def __str__(self):
        return self.station_name

    def as_dict(self):
        publication_code = None
        publication_id = None
        if self.publication:
            publication_code = self.publication.code
            publication_id = self.publication_id

        return {
            'id': self.pk,
            'name': self.station_name,
            'staal_id': self.staal_id,
            'area': self.area,
            'subarea': self.subarea,
            'most_detailed_square_id': self.most_detailed_square_id,
            'publication_code': publication_code,
            'publication_id': publication_id
        }


class Occurrence(models.Model):  # = GEGEVENS in Access
    record_id = models.IntegerField()  # From access, for traceability
    station = models.ForeignKey(Station, on_delete=models.PROTECT)
    species = models.ForeignKey(Species, on_delete=models.PROTECT)
    date = models.DateField(blank=True, null=True)
    individual_count = models.IntegerField(default=1)

    @property
    def date_isoformat(self):
        if self.date:
            return self.date.isoformat()
        else:
            return None

    def as_dict(self):
        most_detailed_square_name = None
        if self.station and self.station.most_detailed_square:
            most_detailed_square_name = self.station.most_detailed_square.name

        publication_year = None
        publication_str = None
        publication_code = None
        publication_id = None
        if self.station and self.station.publication:
            publication_year = self.station.publication.year
            publication_str = self.station.publication.publication
            publication_code = self.station.publication.code
            publication_id = self.station.publication_id

        return {
            "id": self.pk,
            "individual_count": self.individual_count,
            "date": self.date_isoformat,
            "station_id": self.station_id,
            "station_name": self.station.station_name,
            "station_staal_id": self.station.staal_id,
            "station_area": self.station.area,
            "station_subarea": self.station.subarea,
            "station_most_detailed_square": most_detailed_square_name,
            "station_leg": self.station.leg,
            "station_det": self.station.det,
            "species_id": self.species_id,

            "station_publication_year": publication_year,
            "station_publication_code": publication_code,
            "station_publication_str": publication_str,
            "station_publication_id": publication_id
        }

website/views.py
import distutils
import distutils.util

from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from website.models import Species, Occurrence, MgrsSquare, Publication

LEON_BECKER_NAME = "Becker Leon"


def index(request):
    return render(request, 'website/index.html', {'selected_menu_entry': 'index'})


def about(request):
    return render(request, 'website/about.html', {'selected_menu_entry': 'about'})


def explore_by_square(request):
    return render(request, 'website/explore_by_square.html', {'selected_menu_entry': 'squares'})


def square_details(request, square_id):
    square = get_object_or_404(MgrsSquare.objects.prefetch_related('stations_mostdetailed_set__occurrence_set__species'), pk=square_id)
    return render(request, 'website/square_details.html', {
        'selected_menu_entry': 'squares',
        'square': square}
    )


def publication_details(request):
    publication_id = request.GET.get('publication_id')
    publication = get_object_or_404(Publication, pk=publication_id)

    return render(request, 'website/publication_details.html', {'publication': publication})


def square_search(request):
    identifier = request.GET.get('squareIdentifier')
    squares = MgrsSquare.objects.filter(name__icontains=identifier).order_by('name')
    if len(squares) == 1:
        return redirect(squares.first())
    return render(request, 'website/square_search_results.html', {'selected_menu_entry': 'squares', 'results': squares})


def available_species_json(request):
    dictionaries = [obj.as_dict() for obj in Species.objects.all()]
    return JsonResponse({'species': dictionaries})


def _filtered_occ(request):
    species_id = request.GET.get('speciesId')
    filter_out_leon_becker = bool(distutils.util.strtobool(request.GET.get('filterOutLeonBecker', "false")))
    avoid_small_squares = bool(distutils.util.strtobool(request.GET.get("noSmallSquares", "false")))

    occ = Occurrence.objects.all()
    if species_id:
        occ = occ.filter(species_id=species_id)
    if filter_out_leon_becker:
        occ = occ.exclude(station__det=LEON_BECKER_NAME).exclude(station__leg=LEON_BECKER_NAME)

    # For perfs
    if avoid_small_squares:
        occ = occ.select_related('station___5_or_10_square')
    else:
        occ = occ.select_related('station__most_detailed_square')

    return occ


def _extract_int_request(request, param_name):
    """Returns an integer, or None if the parameter doesn't exist or is 'null' """
    val = request.GET.get(param_name, None)
    if val == '' or val == 'null' or val is None:
        return None
    else:
        return int(val)


def _extract_bool_request(request, param_name):
    """Returns an boolean (default to False). Input: 'true' | 'false' """
    val = request.GET.get(param_name, 'false')

    if val == 'true':
        return True
    else:
        return False


def counters_json(request):
    occurrences = _filtered_occ(request)

    return JsonResponse({
        'occurrences': occurrences.count(),
    })


def occurrences_json(request):
    order = request.GET.get('order')
    limit = _extract_int_request(request, 'limit')
    page_number = _extract_int_request(request, 'page_number')

    occurrences = _filtered_occ(request).order_by(order)

    paginator = Paginator(occurrences, limit)  # Show 25 contacts per page.

    page = paginator.get_page(page_number)
    occurrences_dicts = [occ.as_dict() for occ in page.object_list]

    return JsonResponse({'results': occurrences_dicts,
                         'firstPage': page.paginator.page_range.start,
                         'lastPage': page.paginator.page_range.stop,
                         'totalResultsCount': page.paginator.count})


def squares_for_occurrences_json(request):
    """Return squares, including related stations and occurrences. Filtering is done on occ"""
    occurrences = _filtered_occ(request)

    avoid_small_squares = bool(distutils.util.strtobool(request.GET.get("noSmallSquares", "false")))

    encountered_stations = {} # k: station_id val: station dict (see model) + added occurrence list
    encountered_squares = {}  # k: square_id, val: square dict + added stations list

    for occ in occurrences:
        station = occ.station
        # 1. Keep all encountered stations + related occurrences
        occ_as_dict = occ.as_dict()
        if station.pk not in encountered_stations:
            station_dict = station.as_dict()
            station_dict['occurrences'] = [occ_as_dict]
            encountered_stations[station.pk] = station_dict

            # 2. Keep every encountered squares, with related stations
            if avoid_small_squares:
                square = station._5_or_10_square
            else:
                square = station.most_detailed_square

            if square:  # Some stations don't have squares
                if square.pk not in encountered_squares:
                    square_dict = square.as_dict()
                    square_dict['stations'] = [encountered_stations[station.pk]]
                    encountered_squares[square.pk] = square_dict
                else:
                    encountered_squares[square.pk]['stations'].append(encountered_stations[station.pk])
        else:
            encountered_stations[station.pk]['occurrences'].append(occ_as_dict)

    return JsonResponse({'squares': list(encountered_squares.values())})

website/templates/website/_occurrence_table.html
{% if occurrences.exists %}
    <h5>Occurrences</h5>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Record id</th>
            <th scope="col">Species</th>
            <th scope="col">Date</th>
            <th scope="col">Individual count</th>
        </tr>
        </thead>
        <tbody>
        {% for occurrence in occurrences %}
            <tr>
                <td>{{ occurrence.record_id }}</td>
                <td>{{ occurrence.species.scientific_name }}</td>
                <td>{{ occurrence.date|default_if_none:"-" }}</td>
                <td>{{ occurrence.individual_count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

website/templates/website/_station_details.html
<div>
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Name: {{ station.station_name }}</h4>

        <p>
            <b>Staal ID:</b> {{ station.staal_id|default:"/" }}<br>
            <b>Area:</b> {{ station.area|default:"/" }}<br>
            <b>Subarea:</b> {{ station.subarea|default:"/" }}<br>
            <b>UTM squares:</b>
                <b>10km:</b> {{ station.utm10_code|default:"/" }} -
                <b>5km:</b> {{ station.utm5_code|default:"/" }} -
                <b>1km:</b> {{ station.utm1_code|default:"/" }}
            <br>
            <b>Leg: </b> {{ station.leg|default:"/" }}<br>
            <b>Det: </b> {{ station.det|default:"/" }}<br>
            <b>Habitat: </b> {{ station.habitat_description|default:"/" }}<br>
            <b>Start date: </b> {{ station.begin_date|default:"/" }}<br>
            <b>End date: </b> {{ station.end_date|default:"/" }}<br>
        </p>

        <hr>
        {% include "website/_occurrence_table.html" with occurrences=station.occurrence_set.all %}
    </div>

</div>

website/templates/website/about.html
{% extends 'website/base.html' %}
{% load page_fragments %}

{% block content %}
    <div class="container">
        {% get_page_fragment 'about_page_content' %}
    </div>
{% endblock %}

website/templates/website/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
    <title>Arabel</title>
    <style>
        /* Extra styles for footer */
        .footer {
            margin-top: 50px;
            width: 100%;
            height: 60px; /* Set the fixed height of the footer here */
            line-height: 60px; /* Vertically center the text there */
            background-color: #f5f5f5;
        }

        /* Extra styles for custom leaflet legend */
        .legend {
            line-height: 18px;
            color: #555;
        }

        .legend i {
            width: 18px;
            height: 18px;
            float: left;
            margin-right: 8px;
            opacity: 0.7;
        }

        p.legend-entry {
            margin-bottom: 5px;
        }

        .info {
            padding: 6px 8px;
            font: 14px/16px Arial, Helvetica, sans-serif;
            background: white;
            background: rgba(255, 255, 255, 0.8);
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }

        .info h4 {
            text-align: center;
            margin: 0 0 5px;
            color: #777;
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light mb-3" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="{% url 'website-index' %}"> 🕷️ Arabel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if selected_menu_entry == 'index' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'website-index' %}">Explore occurrences</a>
                </li>
                <li class="nav-item {% if selected_menu_entry == 'squares' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'website-squares' %}">Explore by UTM square</a>
                </li>
                <li class="nav-item {% if selected_menu_entry == 'about' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'website-about' %}">About</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}"><span class="oi oi-lock-locked"
                                                                                              title="admin interface"></span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<main role="main">
    {% block content %}{% endblock content %}
</main>

<footer class="footer" >
    <div class="container text-center">
        <span class="text-muted">© 2021 Arabel - <small><a href="https://github.com/niconoe/arabel">Source code</a> version: {{ git_revision_string }}</small></span>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"
        integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ=="
        crossorigin="anonymous"></script>

{% if debug %}
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
{% else %}
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
{% endif %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/6.6.1/d3.min.js"
        integrity="sha512-p/VAUGb1SbLKDesTu1qCZOQZX+4/IYi7UpLDBUqRINK8Xs/ozWN/+fnKDgmRrpLa9OGb6/SNLEL714DFCi/+og=="
        crossorigin="anonymous"></script>

<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>

<script src="{% static 'website/js/arabel-components.js' %}"></script>
</body>
</html>

website/templates/website/explore_by_square.html
{% extends 'website/base.html' %}

{% block content %}
    <div class="container">
        <h1>Search by square</h1>
        <form method="get" action="{% url 'website-square-search' %}">
            <div class="form-group">
                <label for="exampleInputEmail1">UTM/MGRS square identifier:</label>
                <input type="text" class="form-control" name="squareIdentifier" id="squareIdentifier" aria-describedby="identifierHelp" placeholder="31UFR14A">
                <small id="identifierHelp" class="form-text text-muted">Incomplete square identifier such as "32ULV" can be used to perform a search.
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

website/templates/website/index.html
{% extends 'website/base.html' %}
{% load page_fragments %}

{% block content %}
    <div class="container mb-4">
        {% get_page_fragment 'welcome' %}
    </div>

    <div class="container-fluid">
        <div id="app">
            <div class="row">
                <div class="col-3 bg-dark text-white shadow">
                    <form>
                        <h4 class="my-3 text-center">Data selection</h4>
                        <div class="form-group row">
                            <label class="col-sm-6 col-form-label" for="speciesSelect">Species:</label>
                            <select class="form-control col-sm-5 form-control-sm" id="speciesSelect"
                                    v-model="selectedFilters.speciesId">
                                <option v-for="species in availableSpecies" :value="species.id">
                                    [[ species.scientific_name ]]
                                </option>
                            </select>
                        </div>

                        <div class="form-group ">
                            <input type="checkbox" id="checkbox-small-squares" v-model="selectedFilters.noSmallSquares">
                            <label class="col-form-label col-form-label-sm" for="checkbox-small-squares">Map: show data
                                at 5 or 10km
                                resolution only</label>
                        </div>
                        <div class="form-group ">
                            <input type="checkbox" id="checkbox-filter-leon"
                                   v-model="selectedFilters.filterOutLeonBecker">
                            <label class="col-form-label col-form-label-sm" for="checkbox-filter-leon">Filter out Léon
                                Becker</label>
                        </div>
                    </form>
                </div>
                <div class="col-9">
                    <div v-if="selectedSpecies">
                        <species-description :species-data="selectedSpecies" :counters-endpoint="conf.countersURL" :filters="selectedFilters"></species-description>
                    </div>

                    <h4>Results map</h4>
                    <arabel-map :squares-endpoint="conf.getSquaresDataURL" :filters="selectedFilters" :publication-details-url="conf.publicationDetailsUrl"></arabel-map>

                    <h4>Results table</h4>
                    <div v-if="selectedSpecies">

                        <arabel-table :occurrences-endpoint="conf.getOccurrencesDataURL"
                                      :publication-details-url="conf.publicationDetailsUrl"
                                      :filters="selectedFilters"></arabel-table>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        var arabelConf = {
            availableSpeciesURL: '{% url "available-species-json" %}',
            getSquaresDataURL: '{% url "squares-for-occurrences-json" %}',
            getOccurrencesDataURL: '{% url "occurrences-json" %}',
            publicationDetailsUrl: '{% url "website-publication_details" %}',
            countersURL: '{% url "counters-json" %}'
        }

        window.onload = function () {
            new Vue({
                el: '#app',
                components: {
                    ArabelMap: ArabelMap,
                    SpeciesDescription: SpeciesDescription,
                },
                delimiters: ['[[', ']]'],
                data: {
                    selectedFilters: {
                        speciesId: null,
                        noSmallSquares: true,
                        filterOutLeonBecker: false
                    },
                    availableSpecies: [],
                    conf: arabelConf
                },
                computed: {
                    selectedSpecies: function () {
                        return (this.selectedFilters.speciesId ? this.availableSpecies.find(s => s.id == this.selectedFilters.speciesId) : null)
                    }
                },
                mounted: function () {
                    var vm = this;

                    axios
                        .get(vm.conf.availableSpeciesURL)
                        .then(function (response) {
                            vm.availableSpecies = response.data.species
                        })
                },
            })
        }
    </script>
{% endblock content %}

website/templates/website/publication_details.html
{% extends 'website/base.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-success" role="alert">
            <h1>Details about publication with code: {{ publication.code }}</h1>

            <p>
                <b>Access ID:</b> {{ publication.access_id|default:"/" }}<br>
                <b>Code:</b> {{ publication.code|default:"/" }}<br>
                <b>Year:</b> {{ publication.year|default:"/" }}<br>
                <b>Publication: </b>{{ publication.publication }}
            </p>
        </div>

        <small>(close this tab to go back to your search)</small>
    </div>
{% endblock %}

website/templates/website/square_details.html
{% extends 'website/base.html' %}

{% block content %}
    <div class="container">
        <h1>Details about {{ square.name }}</h1>

        {% if square.stations_mostdetailed_set.all.exists %}
            <h2>The following stations reference this square (most detailed)</h2>
            {% for station in square.stations_mostdetailed_set.all %}
                {% include "website/_station_details.html" with station=station %}
            {% endfor %}
        {% else %}
            <p>Sorry, no known station for this square.</p>
        {% endif %}
        <p></p><a href="{% url "website-squares" %}">Return to search form</a></div>
    </div>
{% endblock %}

website/templates/website/square_search_results.html
{% extends 'website/base.html' %}

{% block content %}
    <div class="container">
        <h1>Search results</h1>
        {% if results %}
            <p>Click a square identifier to see the details</p>
            <ul>
                {% for square in results %}
                    <li>
                        <a href="{% url 'website-square-details' square.pk %}">
                            {{ square.name }}
                        </a>

                        ({{ square.stations_mostdetailed_set.count }} station(s))
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Sorry, no results found.</p>
        {% endif %}

        <p></p><a href="{% url "website-squares" %}">Return to search form</a></div>
    </div>
{% endblock %}a